### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by keeferrourke** [RechInformatica/rech-editor-cobol#12]
I just installed this extension for VS Code on Linux and upon loading a cobol file, I got this stack trace.

It would seem like this extension is not catching an error on some object, where the 'trim' property is not defined.

```
(node:16149) UnhandledPromiseRejectionWarning: Error: Request custom/runPreprocExpander failed unexpectedly without providing any details.
    at handleResponse (/home/spooky/.vscode/extensions/rechinformatica.rech-editor-cobol-1.0.16/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/home/spooky/.vscode/extensions/rechinformatica.rech-editor-cobol-1.0.16/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.setImmediate (/home/spooky/.vscode/extensions/rechinformatica.rech-editor-cobol-1.0.16/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
(node:16149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
(node:16149) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 1:04:08 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:11 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:12 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:14 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:15 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:20 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:20 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:20 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:21 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:22 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:37 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
[Error - 1:04:38 p.m.] Request textDocument/onTypeFormatting failed.
  Message: Request textDocument/onTypeFormatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 
```

**Comment by GustavoASC** [comment]
Hello,
First of all, thank you for reporting this issue.
It looks like a problem splitting buffer lines into arrays, since there's a difference in Windows and Linux systems with **\r** and **\n** characters.

We'll solve this as soon as possible.
Regards

**Comment by GustavoASC** [comment]
Fixed on commit https://github.com/RechInformatica/rech-editor-cobol/commit/3fbc22df70b119b671bc1c97ff21c7d466f5d532. It will soon be merged to Master branch and submited to VSCode Market Place.
